# SPDX-FileCopyrightText: 2024 The eminus developers
# SPDX-License-Identifier: Apache-2.0
from collections.abc import Callable
from dataclasses import dataclass
from functools import cached_property
from typing import Any, TypeAlias

from numpy import floating
from numpy.typing import NDArray

_Float: TypeAlias = floating
_ArrayReal: TypeAlias = NDArray[_Float]

@dataclass
class Coefficients:
    theta: _ArrayReal
    omega: float
    e1: float
    e2: float
    e3: float
    e4: float
    e5: float
    d1: float
    d2: float
    d3: float
    d4: float
    d5: float
    c1: float
    c2: float
    c3: float
    b1: float
    b2: float
    b3: float
    b4: float
    a1: float = ...
    a2: float = ...
    a3: float = ...
    a4: float = ...
    a5: float = ...
    a6: float = ...
    @cached_property
    def a0(self) -> float: ...
    @cached_property
    def b5(self) -> float: ...
    @cached_property
    def a(self) -> _ArrayReal: ...
    @property
    def dadtheta(self) -> _ArrayReal: ...
    @cached_property
    def b(self) -> _ArrayReal: ...
    @property
    def dbdtheta(self) -> _ArrayReal: ...
    @cached_property
    def c(self) -> _ArrayReal: ...
    @property
    def dcdtheta(self) -> _ArrayReal: ...
    @cached_property
    def d(self) -> _ArrayReal: ...
    @property
    def dddtheta(self) -> _ArrayReal: ...
    @cached_property
    def e(self) -> _ArrayReal: ...
    @cached_property
    def dedtheta(self) -> _ArrayReal: ...

@dataclass
class Zeta0Coeffs(Coefficients):
    omega: float = ...
    b1: float = ...
    b2: float = ...
    b3: float = ...
    b4: float = ...
    c1: float = ...
    c2: float = ...
    c3: float = ...
    d1: float = ...
    d2: float = ...
    d3: float = ...
    d4: float = ...
    d5: float = ...
    e1: float = ...
    e2: float = ...
    e3: float = ...
    e4: float = ...
    e5: float = ...

@dataclass
class Zeta1Coeffs(Coefficients):
    omega: float = ...
    b1: float = ...
    b2: float = ...
    b3: float = ...
    b4: float = ...
    c1: float = ...
    c2: float = ...
    c3: float = ...
    d1: float = ...
    d2: float = ...
    d3: float = ...
    d4: float = ...
    d5: float = ...
    e1: float = ...
    e2: float = ...
    e3: float = ...
    e4: float = ...
    e5: float = ...

@dataclass
class PhiParams:
    g1: float = ...
    g2: float = ...
    g3: float = ...
    lambda1: float = ...
    lambda2: float = ...

def lda_xc_ksdt(
    n: _ArrayReal,
    T: float = ...,
    zeta0_coeffs: Callable[..., Coefficients] = ...,
    zeta1_coeffs: Callable[..., Coefficients] = ...,
    phi_params: Callable[..., PhiParams] = ...,
    **kwargs: Any,
) -> tuple[_ArrayReal, _ArrayReal, None]: ...
def lda_xc_ksdt_spin(
    n: _ArrayReal,
    zeta: _ArrayReal,
    T: float = ...,
    zeta0_coeffs: Callable[..., Coefficients] = ...,
    zeta1_coeffs: Callable[..., Coefficients] = ...,
    phi_params: Callable[..., PhiParams] = ...,
    **kwargs: Any,
) -> tuple[_ArrayReal, _ArrayReal, None]: ...
def _pade(
    x: _ArrayReal,
    n1: float,
    n2: float,
    n3: float,
    n4: float,
    d1: float,
    d2: float,
) -> _ArrayReal: ...
def _dpade(
    x: _ArrayReal,
    n1: float,
    n2: float,
    n3: float,
    n4: float,
    d1: float,
    d2: float,
) -> _ArrayReal: ...
def _get_theta(
    T: float,
    n: _ArrayReal,
    zeta: _ArrayReal,
) -> _ArrayReal: ...
def _get_dthetadn_up(
    T: float,
    n_up: _ArrayReal,
) -> _ArrayReal: ...
def _get_theta0(
    theta: _ArrayReal,
    zeta: _ArrayReal,
) -> _ArrayReal: ...
def _get_dtheta0dtheta(zeta: _ArrayReal) -> _ArrayReal: ...
def _get_theta1(
    theta: _ArrayReal,
    zeta: _ArrayReal,
) -> _ArrayReal: ...
def _get_dtheta1dtheta0() -> float: ...
def _get_fxc_zeta(
    rs: _ArrayReal,
    p: Coefficients,
) -> _ArrayReal: ...
def _get_dfxc_zetadrs(
    rs: _ArrayReal,
    p: Coefficients,
) -> _ArrayReal: ...
def _get_dfxc_zetadtheta(
    rs: _ArrayReal,
    p: Coefficients,
) -> _ArrayReal: ...
def _get_phi(
    rs: _ArrayReal,
    theta: _ArrayReal,
    zeta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dphidrs(
    rs: _ArrayReal,
    theta: _ArrayReal,
    zeta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dphidtheta(
    rs: _ArrayReal,
    theta: _ArrayReal,
    zeta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dphidzeta(
    rs: _ArrayReal,
    theta: _ArrayReal,
    zeta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_alpha(
    rs: _ArrayReal,
    theta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dalphadrs(
    rs: _ArrayReal,
    theta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dalphadtheta(
    rs: _ArrayReal,
    theta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_g(
    rs: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dgdrs(
    rs: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_lambda(
    rs: _ArrayReal,
    theta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dlambdadrs(
    rs: _ArrayReal,
    theta: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
def _get_dlambdadtheta(
    rs: _ArrayReal,
    phi_params: PhiParams,
) -> _ArrayReal: ...
