# SPDX-FileCopyrightText: 2021 Wanja Timm Schulze <wangenau@protonmail.com>
# SPDX-License-Identifier: Apache-2.0
from typing import Callable

from .logger import log as log

# Add type hints for all properties and methods of the ConfigClass to the module
# This allows type checkers to see that the module has said attribute
use_torch: bool
use_gpu: bool
use_pylibxc: bool
threads: int
verbose: int | str
info: Callable[[], None]

class ConfigClass:
    def __init__(self) -> None: ...
    @property
    def use_torch(self) -> bool: ...
    @use_torch.setter
    def use_torch(self, value: bool) -> None: ...
    @property
    def use_gpu(self) -> bool: ...
    @use_gpu.setter
    def use_gpu(self, value: bool) -> None: ...
    @property
    def use_pylibxc(self) -> bool: ...
    @use_pylibxc.setter
    def use_pylibxc(self, value: bool) -> None: ...
    @property
    def threads(self) -> int: ...
    @threads.setter
    def threads(self, value: int) -> None: ...
    @property
    def verbose(self) -> str: ...
    @verbose.setter
    def verbose(self, value: int | str) -> None: ...
    def info(self) -> None: ...
