# SPDX-FileCopyrightText: 2021 Wanja Timm Schulze <wangenau@protonmail.com>
# SPDX-License-Identifier: Apache-2.0
import numpy as np
from numpy.typing import NDArray

from .typing import Array1D, Array2D, IntArray

class KPoints:
    lattice: str
    a: float | Array2D | None
    is_built: bool
    def __init__(
        self,
        lattice: str,
        a: float | Array2D | None = ...,
    ) -> None: ...
    @property
    def kmesh(self) -> NDArray[np.int64]: ...
    @kmesh.setter
    def kmesh(self, value: IntArray) -> None: ...
    @property
    def wk(self) -> NDArray[np.float64]: ...
    @wk.setter
    def wk(self, value: Array1D) -> None: ...
    @property
    def k(self) -> NDArray[np.float64]: ...
    @k.setter
    def k(self, value: Array2D) -> None: ...
    @property
    def Nk(self) -> int: ...
    @Nk.setter
    def Nk(self, value: int) -> None: ...
    @property
    def kshift(self) -> NDArray[np.int64]: ...
    @kshift.setter
    def kshift(self, value: Array1D) -> None: ...
    @property
    def gamma_centered(self) -> bool: ...
    @gamma_centered.setter
    def gamma_centered(self, value: bool) -> None: ...
    @property
    def path(self) -> str | None: ...
    @path.setter
    def path(self, value: str | None) -> None: ...
    @property
    def k_scaled(self) -> NDArray[np.float64]: ...
    def build(self) -> KPoints: ...
    kernel = build

def kpoint_convert(
    k_points: Array2D,
    lattice_vectors: Array2D,
) -> NDArray[np.float64]: ...
def monkhorst_pack(nk: IntArray) -> NDArray[np.float64]: ...
def gamma_centered(nk: IntArray) -> NDArray[np.float64]: ...
def bandpath(kpts: KPoints) -> NDArray[np.float64]: ...
def kpoints2axis(kpts: KPoints) -> tuple[NDArray[np.float64], NDArray[np.float64], list[str]]: ...
def get_brillouin_zone(lattice_vectors: NDArray[np.float64]) -> NDArray[np.float64]: ...
